# Use root/example as user/password credentials
version: '3.1'

volumes:
  dockvol:
    #external: true
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
      - MYSQL_DATABASE=database
    volumes:
      #- /dockvol/dc-mysql:/var/lib/mysql
      - dockvol:/var/lib/mysql
    ports:
      - 3306:3306


  adminer:
    image: adminer
    restart: always
    ports:
      - 7010:8080

  mysqlexporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=root:abcd1234@(db:3306)/database
