version: '3'
services:

  # jenkins image
  jenkins:
    container_name: jenkins
    #image: jenkins/jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - 8080:8080
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net

  # centos image to simulate remote site
  remote_host:
    container_name: remote-host
    image: remote-host
    volumes:
      - $PWD/aws-s3.sh:/tmp/script.sh
    build:
      context: centos7
    networks:
      - net

  # mysql image
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net

  # web image based on the remote-host image and install php
  web:
    container_name: web
    image: ansiable-web
    build:
      context: jenkins-ansible/web/
    ports:
      - "80:80"
    networks:
      - net
networks:
  net:
