version: "3.7"

services:
  # jupyterlab with pyspark
  pyspark:
    image: jupyter/pyspark-notebook:latest
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "9999:8888"
    volumes:
      - /dockvol/dc-spark/data:/home/jovyan/work
